[application]

[web.app]

# HTML title tag content
title = "rust-fullstack-core"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["/tailwind.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Additional CSS style files
style = ["/tailwind.css"]

# Javascript code file
# serve: [dev-server] only
script = []
